# From  ubuntu:22.04
FROM python:3.11

COPY . /digits/
# 
# RUN apt-get update
# RUN apt-get install -y python3
RUN pip3 install -r ./digits/requirements.txt

WORKDIR /digits

# CMD ["pytest"]

RUN export FLASK_APP=API/hello
CMD ["flask", "run"]

# cmd ["echo", "1st cmd line"]